### ISSUE TITLE
Message: Extension Update

### ISSUE THREAD

**Issue by jakceo** [samapraku/lhc_gcm_extension#2]
I updated the extension, settings etc. I am receiving the notifications but this red message remains: "Extension Update: Click me for more detais".
![screenshot_20181218-191627](https://user-images.githubusercontent.com/32709667/50187250-aab12780-0304-11e9-8808-d5bd2de2f39c.png)
![screenshot_20181218-192322](https://user-images.githubusercontent.com/32709667/50187253-ad138180-0304-11e9-9626-2d0b74e2cf60.png)

**Comment by samapraku** [comment]
@jakceo sorry for experiencing this issue.

The issue is because the app checks the version number of the extension each time it is opened. 
If there is slow or no internet connection, it returns an error and the app shows the notice that the extension has to be updated.
I would have to save the version number of the extension  in the database after checking from the installed server to resolve the issue but I haven't been able to work on it.

For now, you can ignore the notice. I will find some time to fix it.

**Comment by mobentec** [comment]
I too am experiencing this issue.  Were you able to fix this issue?

**Comment by mobentec** [comment]
After uploading the extensions, you need to give 777 permissions to settings.ini.php file located in: /lhc_web/extension/gcm/settings. :-)  This allows push notifications to work.

I am, however, still getting the red message at the bottom of the app window.

**Comment by asscomp** [comment]
Forgive me for not responding. I stopped using the application. Very grateful for your kindness in giving a return.
